### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by francesco74** [fever-ch/go-google-sites-proxy#1]
Some changes in google sites make the proxy not working anymore, redirecting to google sites home page

**Comment by rbarazzutti** [comment]
Hi Francesco74, 

Thanks for the feedback. Google changed a few things in Google Sites and Go-Google-Sites-Proxy was impacted. A temporary patch is being tested on [https://ggsp.fever.ch/](https://ggsp.fever.ch/) and some others sites. 

Cheers,

Raphaël

**Comment by rbarazzutti** [comment]
no feedback from francesco74. closing issue.

**Comment by rbarazzutti** [comment]
no feedback from @francesco74. closing issue.

**Comment by leoj3n** [comment]
@francesco74 It seems google has added some code to that JS file to check its own integrity:

https://www.gstatic.com/_/atari/_/js/k=atari.vw.en_US.A9bve80bs0s.O/rt=j/d=1/rs=AGEqA5l1ILRT52ijkqpDvueTFq7woUdQYw/m=view

It redirects the page if the location is not on `google.com` or perhaps if the script itself has been included with a different `src`. You will see different behavior if you strip out that `<script>` from the HTML, curl it locally, and load it in the same place with a `src` pointing to the local file. It will `throw Error` and trigger `_._DumpException(e)` which needs to be changed to `window._DumpException(e)` to see the stack trace. The error strings are cryptic like `throw Error("kb")`:

```
e||(e=document.getElementsByTagName("script"),e=FA(e[e.length-1].src));if(!e)throw Error("kb");e=new AA(e);
```

The same script is loaded on both https://demo.lexnetcrm.com/ and https://sites.google.com/view/go-gsites-proxy so this same script is served up for a custom domain.

@rbarazzutti If you're working on a patch, can you tell us where to find it?

EDIT:

The redirection also appears to break the wayback machine and even google's own cache:

- https://web.archive.org/save/https://sites.google.com/view/go-gsites-proxy
- [google cache](https://webcache.googleusercontent.com/search?q=cache:msCtfExa8qoJ:https://sites.google.com/view/go-gsites-proxy/+&cd=1&hl=en&ct=clnk&gl=us)

**Comment by leoj3n** [comment]
Here, I made a proxy that works (only tested local):

https://github.com/leoj3n/new-google-sites-proxy

EDIT:

FYI, [this hack](https://github.com/leoj3n/new-google-sites-proxy/blob/f9970a623eddee9b1962d707254ce4fa83a9af83/index.js#L17-L26) replaces a string in the `_at_config` variable, which stops the site from reloading.
